
export const LOADED_TRENDING_GIFS = "LOADED_TRENDING_GIFS";

export const LOADED_SEARCH_GIFS = "SEARCH_GIFS";

export const SET_FIlTER = "SET_FILTER"

export const CLEAR_FILTER = "CLEAR_FILTER"

export const ADD_SEARCH = 'ADD_SEARCH'

export const SELECT_SEARCH = 'SELECT_SEARCH'


export const UPDATE_FILTER_LIST = "UPDATE_FILTER_LIST"